/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as HaciendaRouteImport } from './routes/hacienda'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as ApiPublicRobotsRouteImport } from './routes/api/public/robots'
import { Route as ApiPublicSitemapRouteImport } from './routes/api/public/sitemap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const HaciendaRoute = HaciendaRouteImport.update({
  id: '/hacienda',
  path: '/hacienda',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobotsRoute = ApiPublicRobotsRouteImport.update({
  id: '/api/public/robots',
  path: '/api/public/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapRoute = ApiPublicSitemapRouteImport.update({
  id: '/api/public/sitemap',
  path: '/api/public/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRoute
  '/galeria': typeof GaleriaRoute
  '/hacienda': typeof HaciendaRoute
  '/menu': typeof MenuRoute
  '/nosotros': typeof NosotrosRoute
  '/reservas': typeof ReservasRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRoute
  '/galeria': typeof GaleriaRoute
  '/hacienda': typeof HaciendaRoute
  '/menu': typeof MenuRoute
  '/nosotros': typeof NosotrosRoute
  '/reservas': typeof ReservasRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRoute
  '/galeria': typeof GaleriaRoute
  '/hacienda': typeof HaciendaRoute
  '/menu': typeof MenuRoute
  '/nosotros': typeof NosotrosRoute
  '/reservas': typeof ReservasRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/eventos'
    | '/galeria'
    | '/hacienda'
    | '/menu'
    | '/nosotros'
    | '/reservas'
    | '/api/public/robots'
    | '/api/public/sitemap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/eventos'
    | '/galeria'
    | '/hacienda'
    | '/menu'
    | '/nosotros'
    | '/reservas'
    | '/api/public/robots'
    | '/api/public/sitemap'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/eventos'
    | '/galeria'
    | '/hacienda'
    | '/menu'
    | '/nosotros'
    | '/reservas'
    | '/api/public/robots'
    | '/api/public/sitemap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  EventosRoute: typeof EventosRoute
  GaleriaRoute: typeof GaleriaRoute
  HaciendaRoute: typeof HaciendaRoute
  MenuRoute: typeof MenuRoute
  NosotrosRoute: typeof NosotrosRoute
  ReservasRoute: typeof ReservasRoute
  ApiPublicRobotsRoute: typeof ApiPublicRobotsRoute
  ApiPublicSitemapRoute: typeof ApiPublicSitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hacienda': {
      id: '/hacienda'
      path: '/hacienda'
      fullPath: '/hacienda'
      preLoaderRoute: typeof HaciendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robots': {
      id: '/api/public/robots'
      path: '/api/public/robots'
      fullPath: '/api/public/robots'
      preLoaderRoute: typeof ApiPublicRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap': {
      id: '/api/public/sitemap'
      path: '/api/public/sitemap'
      fullPath: '/api/public/sitemap'
      preLoaderRoute: typeof ApiPublicSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  EventosRoute: EventosRoute,
  GaleriaRoute: GaleriaRoute,
  HaciendaRoute: HaciendaRoute,
  MenuRoute: MenuRoute,
  NosotrosRoute: NosotrosRoute,
  ReservasRoute: ReservasRoute,
  ApiPublicRobotsRoute: ApiPublicRobotsRoute,
  ApiPublicSitemapRoute: ApiPublicSitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
